# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'web'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'anhamilt(249572df-0ca0-46f8-8a3d-f46987d7fc85)'
    azureContainerRegistry: '{"loginServer":"anhamiltc1t1.azurecr.io", "id" : "/subscriptions/249572df-0ca0-46f8-8a3d-f46987d7fc85/resourceGroups/mcr-global-rg/providers/Microsoft.ContainerRegistry/registries/anhamiltc1t1"}'
    dockerComposeFile: '**/Dockerfile'
    action: 'Build services'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: Docker@2
  inputs:
    containerRegistry: 'AnhamiltAcrConnection'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'AnhamiltAcrConnection'
    repository: 'internal/anhamilt'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'build$(Build.BuildId)'
- task: Docker@2
  inputs:
    containerRegistry: 'AnhamiltAcrConnection'
    command: 'logout'